name: Build

on:
  workflow_call:
    inputs:
      artifact_suffix:
        description: 'Suffix for artifact names'
        required: false
        default: ''
        type: string
      retention_days:
        description: 'Artifact retention days'
        required: false
        default: 14
        type: number

env:
  BUILD_TYPE: Release

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }} --target OFS-SE

      - uses: actions/upload-artifact@v4
        with:
          name: build-windows${{ inputs.artifact_suffix }}
          path: bin/Release/*
          retention-days: ${{ inputs.retention_days }}

  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libmpv-dev libglvnd-dev

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }} --target OFS-SE

      - uses: actions/upload-artifact@v4
        with:
          name: build-linux${{ inputs.artifact_suffix }}
          path: bin/OFS-SE
          retention-days: ${{ inputs.retention_days }}

  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Dependencies
        run: brew install llvm mpv

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_POLICY_VERSION_MINIMUM=3.5

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }} --target OFS-SE

      - uses: actions/upload-artifact@v4
        with:
          name: build-macos${{ inputs.artifact_suffix }}
          path: bin/OFS-SE.app
          retention-days: ${{ inputs.retention_days }}
